CREATE DATABASE IF NOT EXISTS todo_test_db;
GRANT ALL PRIVILEGES ON todo_test_db.* TO 'todo_usr'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS todo_test_db.todos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    is_done BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);